config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :polls, only: %i[new show create update]
  resources :questions, only: %i[new show create update]

  patch '/polls/:poll_id/questions_done', to: 'polls#questions_done', as: 'questions_done'
  post '/polls/:poll_id/add_voters', to: 'voters#create', as: 'add_voters'
  resources :contacts, only: %i[new index show create update]
  resources :answers, only: %i[new show update create destroy]
  resources :contact_lists

  # get '/contacts/index', to: 'contacts#index'
  # post 'contacts', to: 'contacts#create'
  # post 'contact_list', to: 'contact_list#create'


  get '/polls/:poll_id/vote/:token', to: 'opinions#new', as: :opinion
  post '/polls/:poll_id/vote/:token', to: 'opinions#create'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_existingquestion.html.erb
<div class="question-box">

  <div class="question-number"> <%= existingquestion.title %> </div>

  <p class="question-title" ><%= existingquestion.content %></p>

  <% Answer.where(question_id: existingquestion.id).each do |a| %>
    <div> • <%= a.content %></div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer main-card">
  <div class="footer-btn"><i class="fas fa-chevron-left"></i></div>
  <div class="footer-btn"><i class="fas fa-plus"></i></div>
  <div class="footer-btn"><i class="fas fa-chevron-right"></i></div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag 'logo.png' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Contacts", contacts_path, class: "dropdown-item" %>
            <%= link_to "My polls", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_newquestion.html.erb
<%# I need to have 2 separate fields ; 1 for question params, another one for answers (linked to the said question) %>
<div style="margin-bottom:60px" class="questioncard">
    <%= simple_form_for @question do |f| %>
      <div style="color:white; padding:15px"><%= f.input :title, label: 'Your question title please:', error: 'This question title is not valid'%></div>
      <div style="color:white; padding:15px"><%= f.input :answers, input_html: { value: "", name: "answers[]"}, error: 'This answer is not valid' %> <a class='add_answer' >+ add an answer</a></div>

      <%= hidden_field_tag(:poll_id, @poll.id) %>
      <%# <%= f.button :submit, "+ Add a question", style: "margin: 0 auto; width: 250px; font-weight: bold; color: white;" %>
    <% end %>
</div>

<div class="footer main-card d-flex justify-content-around" >

<button class="button_send_question", style="font-weight: bold; color: #5f50df;">+ Add a question</button>

<%= link_to questions_done_path(@poll), method: :patch do %>
  <div class="footer-btn"><i class="far fa-check-circle w-16 fa-2x" id='check-icon'></i></div>
<% end %>

</div>






<%# I need fields to have 2 answers set when the questions are "created" and they would need to be attached to this Q? instance
which means that the way I see it, a new question in instantly created (with an ID in DB) %>
<%# fields would be "simple" HTML, as I'm  not quite sure yet how to do so with sff %>

app/views/shared/_newvoters.html.erb
<div style="margin-bottom:60px" class="voterscard">
  <%= simple_form_for @poll, as: :poll, method: :post, url: add_voters_path(@poll) do |f| %>
    <div style="color:white; padding: 15px"><%= hidden_field_tag(:poll_id, @poll.id) %></div>
    <div style="color:white; padding: 15px"><%= f.input :voters, input_html: { value: "", name: "voters[]"}, hint: '10-200 characters' %> <div><a class='add_voter' >+ add a voter</a></div>
    <%# <div> <%= f.button :submit, "Update Poll", style: "margin: 0 auto; width: 250px; font-weight: bold; color: white;" %>
  <% end %>
</div>

<div class="footer main-card d-flex justify-content-around" >

<button class="button_update_poll", style="font-weight: bold; color: #5f50df;">Update Poll</button>

     <%= link_to questions_done_path(@poll), method: :patch do %>
        <div class="footer-btn"><i class="far fa-check-circle w-16 fa-2x" id='check-icon'></i></div>
      <% end %>
  </div>
</div>

app/views/shared/_ongoingvote.html.erb
<div class="head">
<div> Ongoing vote!</div>
<div>Waiting for voters' input...</div>
</div>

<div class="d-flex justify-content-center gif">
  <%= image_tag "pending.gif" %>
</div>

<div style="text-align:center;font-size:20px;margin-bottom:60px">
  <button onClick="window.location.reload();">Refresh page</button>
</div>

app/views/shared/_pollquestion.html.erb
<div class="results-card">
  <% answers = [] %>
  <% contents = [] %>
  <% Answer.where(question_id: pollquestion.id).each do |answer| %>
    <% votes = Opinion.where(answer_id: answer.id) %>
    <% answers << votes.count %>
    <% contents << answer.content.gsub("\'", "&#8216") %>
    <% total = Opinion.where(question_id: pollquestion.id).count %>
  <% end %>
  <div class="results-title">
    <h2><%= pollquestion.title %></h2>
  </div>
  <div class="results-chart">
    <%# the single quotes around the attribute of data-contents is actually quite important and needs to be placed, otherwise it breaks the graphs %>
    <canvas class="my-chart" data-contents='<%= sanitize contents.to_json %>' data-answers=<%= sanitize answers.to_json %>><%= pollquestion.title %></canvas>
  </div>
</div>

app/views/shared/_stepper.html.erb
<div class="stepper">

  <%= sanitize "
    <div class='step completed'>
      <div class='step-label'></div>
    </div>" *  (poll.get_step_number - 1)
  %>

  <div class='step active'>
    <div class='step-label'></div>
  </div>

  <%= sanitize "
    <div class='step'>
      <div class='step-label'></div>
    </div>" * (4 - poll.get_step_number )
  %>

</div>


<!-- PENDING QUESTIONS_DONE SENT ONGOING -->

app/views/shared/_votecompleted.html.erb
<div class="main-text">
  <div>Thanks for voting!</div>
</div>

<div style="text-align:center; margin-bottom:60px">
  <%= image_tag "checkmark.gif", :width => 100, :height=>100  %>
</div>

<div class="bottom-text">Your input will remain anonymous, and your data will be deleted 24H after the vote's expiration date.  </div>

app/views/shared/_votestatus_test.erb
<div class="poll-presentation">
  <h1>Your vote was successfully sent.</h1>

  <h3>Your vote will be updated as soon as every voter expressed their opinion.</h3>
</div>