config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :polls, only: %i[new show create update]
  resources :questions, only: %i[new show create update]

  patch '/polls/:poll_id/questions_done', to: 'polls#questions_done', as: 'questions_done'
  post '/polls/:poll_id/add_voters', to: 'voters#create', as: 'add_voters'
  resources :contacts, only: %i[new index show create update]
  resources :answers, only: %i[new show update create destroy]
  resources :contact_lists

  # get '/contacts/index', to: 'contacts#index'
  # post 'contacts', to: 'contacts#create'
  # post 'contact_list', to: 'contact_list#create'


  get '/polls/:poll_id/vote/:token', to: 'opinions#new', as: :opinion
  post '/polls/:poll_id/vote/:token', to: 'opinions#create'

  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/pages/home.html.erb
  <div class="d-flex flex-column align-items-center" >
    <%= image_tag "logo.png", alt: "Logo FastDem", width: 250, style: "margin-top: 15px"%>
  </div>

  <h3 class="row justify-content-md-center headline insetshadow mt-3">Online Vote made simple.</h3>


  <div class="card-home-page">
    <div style="margin-bottom: 25px; font-size: 20px"> FastDemocracy is a vote tool designed to save you some time and allow you to keep private data really private, as it should always be (wink wink Mark Z. 😘 )</div>


    <div style="font-size: 20px">Please keep in mind the results of your vote will be deleted 24h after it is completed. 😎</div>
  </div>


  <div class="d-flex flex-column align-items-center" style="margin-bottom:150px">
    <%= link_to "Start", polls_path, method: :post, class: "btn btn-primary btn-lg", style: "border-radius: 7px" %>
  </div>